version: '3.3'
services:
  tsg_nodejs:
    image: node:latest
    working_dir: /usr/src/app
    depends_on:
      - tsg_postgis
    volumes:
      - ./nodejs:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm i && npm i -g nodemon && nodemon"

  tsg_postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      # - POSTGRES_DB=geodb
    ports:
      - 5433:5432
    volumes:
      - ./postgis:/docker-entrypoint-initdb.d
